top_100_crypto_list = [
    "BTC-USD", "ETH-USD", "BNB-USD", "SOL1-USD", "AVAX-USD",
    "XRP-USD", "ADA-USD", "DOT1-USD", "LUNA1-USD", "LINK-USD",
    "LTC-USD", "BCH-USD", "DOGE-USD", "MATIC-USD", "FTT-USD",
    "SHIB-USD", "VET-USD", "TRX-USD", "THETA-USD", "ATOM1-USD",
    "XLM-USD", "ALGO-USD", "ICP-USD", "WBTC-USD", "FIL-USD",
    "ETC-USD", "BUSD-USD", "XTZ-USD", "AXS-USD", "CAKE-USD",
    "CETH-USD", "CRO-USD", "EGLD-USD", "QNT-USD", "SAND-USD",
    "MKR-USD", "WAVES-USD", "DAI-USD", "UST-USD", "CHZ-USD",
    "HBAR-USD", "ONE1-USD", "FLOW-USD", "TUSD-USD", "ENJ-USD",
    "HT-USD", "CEL-USD", "BAT-USD", "IOST-USD", "AMP-USD",
    "MANA-USD", "SUSHI-USD", "ZIL-USD", "RVN-USD", "KLAY-USD",
    "NEAR-USD", "ONT-USD", "SC-USD", "ICX-USD", "YFI-USD",
    "DODO-USD", "ZRX-USD", "AR-USD", "PERP-USD", "NXM-USD",
    "HOT-USD", "VRA-USD", "SETH-USD", "CKB-USD", "BAL-USD",
    "PAX-USD", "UMA-USD", "RSR-USD", "MUSD-USD", "1INCH-USD",
    "SUSHI2-USD", "TWT-USD", "BNT-USD", "LUSD-USD", "TVK-USD",
    "SRM-USD", "PAXG-USD", "UBT-USD", "RUNE-USD", "MIR-USD",
    "POWR-USD", "ANKR-USD", "WRX-USD", "POLY-USD", "EWT-USD",
    "USDN-USD", "STEEM-USD", "QSP-USD", "AUDIO-USD", "POLS-USD",
    "IQ-USD", "MDX-USD", "OGN-USD"
]
sp500_stocks = [
    "AAPL", "MSFT", "AMZN", "GOOGL", "GOOG", "FB", "TSLA", "BRK.B", "NVDA", "JPM",
    "JNJ", "V", "MA", "PYPL", "DIS", "ADBE", "HD", "BAC", "CMCSA", "XOM",
    "UNH", "INTC", "VZ", "NFLX", "CRM", "KO", "T", "PEP", "MRK", "ABBV",
    "PFE", "WMT", "NKE", "CVX", "TMO", "CSCO", "MDT", "ORCL", "AMGN", "ABT",
    "BMY", "ACN", "LRCX", "NEE", "WFC", "TXN", "DHR", "PM", "MCD", "AVGO",
    "IBM", "COST", "HON", "LIN", "UNP", "LLY", "UPS", "SBUX", "MMM", "BLK",
    "QCOM", "GS", "CAT", "BA", "RTX", "AXP", "LOW", "MS", "CVS", "ANTM",
    "BDX", "CHTR", "CI", "TGT", "NOW", "GILD", "DUK", "PLD", "USB", "SPGI",
    "SYK", "D", "ISRG", "SO", "CB", "TMO", "MO", "FIS", "EQIX", "BSX",
    "MMC", "DOW", "VRTX", "ZTS", "BDX", "ADP", "APD", "WBA", "VRTX", "SPG",
    "ISRG", "EW", "MET", "REGN", "TJX", "AON", "CTSH", "PRU", "DE", "ATVI",
    "EOG", "GD", "AEP", "LMT", "FISV", "GM", "CSX", "SCHW", "ECL", "LHX",
    "KMB", "CCI", "WMB", "NSC", "RTX", "KLAC", "NEM", "A", "SO", "ZTS",
    "BKNG", "MMC", "ICE", "ANTM", "IDXX", "STZ", "ROST", "PSX", "TEL", "ROP",
    "AIG", "ESS", "ROST", "PSX", "TEL", "ROP", "AIG", "ESS", "ROST", "PSX",
    "TEL", "ROP", "AIG", "ESS", "REG", "ALL", "DLR", "CBRE", "WLTW", "ESS",
    "CPRT", "WELL", "CFG", "PAYX", "VFC", "AIZ", "AWK", "BKR", "EXC", "AFL",
    "EBAY", "DAL", "ALGN", "VAR", "ED", "CME", "CDNS", "SRE", "WY", "WLTW",
    "ORLY", "TFC", "RF", "ITW", "MTD", "HLT", "VRSK", "WEC", "WST", "HUM",
    "FRC", "ANSS", "BAX", "KEYS", "LH", "AMP", "ALB", "MNST", "ALXN", "MSCI",
    "KMI", "HCA", "HSY", "LUMN", "XEL", "ETR", "EOG", "TRV", "LNT", "PH",
    "LYB", "DLTR", "TDG", "SYY", "AME", "MKC", "STT", "WAB", "CNC", "WDC",
    "MLM", "NVR", "CMI", "BXP", "FTV", "FE", "VRTX", "ANET", "ZBH", "FITB",
    "EXR", "DLR", "UDR", "APH", "ULTA", "RMD", "JKHY", "O", "RCL", "REG",
    "JCI", "IPGP", "QRVO", "TROW", "NUE", "CMS", "ATO", "PGR", "IQV", "RSG",
    "AWK", "MPC", "ESS", "CNC", "AIV", "MTB", "ARE", "HSIC", "ESS", "BKR",
    "GPC", "SYF", "PKG", "DTE", "VMC", "WRB", "ALK", "DFS", "DRI", "HII",
    "TRMB", "KSU", "AMP", "ROL", "SIVB", "PPG", "AEE", "CTXS", "IPG", "LYV",
    "FLT", "PNW", "DVA", "OKE", "CFG", "CTLT", "CINF", "TXT", "IEX", "ZBRA",
    "FLT", "LNT", "LDOS", "EXPD", "KHC", "HSIC", "BIO", "NDAQ", "KMX", "CNP",
    "PPL", "ODFL", "VNO", "LW", "WRK", "GRMN", "BR", "KMX", "APTV", "RE",
    "ALLE", "IP", "BF.B", "AJG", "SJM", "VRSN", "CHD", "ABC", "NRG", "FFIV",
    "K", "IPG", "PNR", "ED", "AVY", "AME", "DVA", "FMC", "COG", "RHI",
    "ED", "SJM", "TSN", "MAS", "HII", "GWW", "AOS", "ZION", "SEE", "OMC",
    "HIG", "LKQ", "ETN", "DISCK", "DOV", "NTAP", "CMA", "AOS", "CAG", "LNC",
    "CTLT", "ESS", "WAB", "MGM", "BIO", "INCY", "CDW", "RJF", "PKG", "HBAN",
    "MAA", "WHR", "FLIR", "TRV", "PFG", "AES", "ETFC", "FRT", "DRE", "NLOK",
    "PFG", "NCLH", "BWA", "WHR", "QRVO", "LW", "TSCO", "VAR", "F", "IRM",
    "PBCT", "CDW", "LDOS", "NLSN", "HSY", "NWL", "BF.B"]
nifty50_stocks = [
    "ADANIPORTS.NS",
    "ASIANPAINT.NS",
    "AXISBANK.NS",
    "BAJAJ-AUTO.NS",
    "BAJFINANCE.NS",
    "BAJAJFINSV.NS",
    "BPCL.NS",
    "BHARTIARTL.NS",
    "BRITANNIA.NS",
    "CIPLA.NS",
    "COALINDIA.NS",
    "DIVISLAB.NS",
    "DRREDDY.NS",
    "EICHERMOT.NS",
    "GRASIM.NS",
    "HCLTECH.NS",
    "HDFC.NS",
    "HDFCBANK.NS",
    "HEROMOTOCO.NS",
    "HINDALCO.NS",
    "HINDUNILVR.NS",
    "HDFCLIFE.NS",
    "ICICIBANK.NS",
    "INDUSINDBK.NS",
    "INFY.NS",
    "ITC.NS",
    "JSWSTEEL.NS",
    "KOTAKBANK.NS",
    "LT.NS",
    "M&M.NS",
    "MARUTI.NS",
    "NTPC.NS",
    "NESTLEIND.NS",
    "ONGC.NS",
    "POWERGRID.NS",
    "RELIANCE.NS",
    "SBILIFE.NS",
    "SHREECEM.NS",
    "SBIN.NS",
    "SUNPHARMA.NS",
    "TCS.NS",
    "TATACONSUM.NS",
    "TATAMOTORS.NS",
    "TATASTEEL.NS",
    "TECHM.NS",
    "TITAN.NS",
    "ULTRACEMCO.NS",
    "UPL.NS"
]

